name: Database Migration

on:
  push:
    branches:
      - master
    paths:
      - migrations

jobs:
  database-migration:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Cloning repository source code
        uses: actions/checkout@v4
      - name: Setting up golang environment
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: Install golang-migrate cli tool
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - name: Run database migration
        run: migrate -path ./migrations -database "${{ secrets.DATABASE_URL }}" up
